version: 2
jobs:
  dependency_setup: &dependency_setup
    steps:
      - run: yarn install --exact
      - run: yarn bootstrap
  build: &build
    steps:
      - run: yarn build
      - run: yarn link
  setup:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      <<: *dependency_setup
      <<: *build
workflows:
  version: 2
  setup_:
    jobs:
      - setup