version: 2
jobs:
  setup:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run: yarn install --exact
      - run: yarn bootstrap
  build:
    steps:
      - run: yarn build
      - run: yarn link
workflows:
  version: 2
  setup_:
    jobs:
      - setup
      - build:
          requires:
            - setup