version: 2
aliases:
  - &docker
    - image: circleci/node:10.16.0
jobs:
  setup:
    docker: *docker
    steps:
      - checkout
      - run: ls -a
      - run: yarn install --exact
      - run: yarn bootstrap
      - run: mkdir artifacts
      - store_artifacts:
          path: artifacts/packages
      - store_artifacts:
          path: artifacts/lerna.json
      - store_artifacts:
          path: artifacts/package.json
  build:
    docker: *docker
    steps:
      - run: ls
      - run: yarn build
      - run: yarn link
workflows:
  version: 2
  setup_and_build:
    jobs:
      - setup
      - build:
          requires:
            - setup