version: 2
aliases:
# Executor
  - &docker
    - image: circleci/node:10.16.0
# Persistance
  - &persist_to_workspace
          root: for-the-north
          paths:
           - packages
           - package.json
           - lerna.json
## Job steps: setup
  - &setup_steps
      - checkout
      - run: mkdir for-the-north
      - run: mv packages for-the-north
      - run: mv package.json for-the-north
      - run: mv lerna.json for-the-north
      - persist_to_workspace: *persist_to_workspace
## Job steps: build
  - &build_steps
      - attach_workspace:
          at: for-the-north
      - run: cd for-the-north
      - run: yarn install --exact
      - run: yarn bootstrap
      - run: yarn build
      - run: yarn link


jobs:
  setup:
    docker: *docker
    steps: *setup_steps
  build:
    docker: *docker
    steps: &build_steps
workflows:
  version: 2
  setup_and_build:
    jobs:
      - setup
      - build:
          requires:
            - setup