 version: 2
 jobs:
   one:
     docker:
       - image: circleci/node:10.16.0
     steps:
       - checkout
       - run: echo "A first hello"
    two:
     docker:
       - image: circleci/node:10.16.0
     steps:
       - checkout
       - run: echo "A first chido"
  workflows:
    version: 2
    one_and_two:
      jobs:
        - one
        - two