const SUNNY_DESERT = "SUNNY_DESERT"
const SNOWY_PLAIN = "SNOWY_PLAIN"
const BELLADONA = "BELLADONA"
const SLIM = "SLIM"
const NIGHT_DARK = "NIGHT_DARK"

export { SLIM, BELLADONA, SNOWY_PLAIN, SUNNY_DESERT, NIGHT_DARK }
